### ISSUE TITLE
[Feature Request] Read chart dependencies

### ISSUE THREAD

**Issue by jhamman** [jacobtomlinson/gha-read-helm-chart#3]
With Helm 3, chart dependencies are now included in the `Chart.yaml`, rather than in a separate file. Would it be possible to expose the dependencies (and their values) in this actions data structure? I'm envisioning something like this working:

```yaml
steps:
- uses: actions/checkout@master
- name: Read Helm Chart
  id: chart
  uses: jacobtomlinson/gha-read-helm-chart@master
  with:
    path: path/to/chart
- name: Print outputs
    run: |
    echo "Version - ${{ steps.chart.outputs.version }}"
    echo "Dependency Version - ${{ steps.chart.outputs.dependencies.dask.version }}"
```
