### ISSUE TITLE
[Feature Request] Read chart values

### ISSUE THREAD

**Issue by jhamman** [jacobtomlinson/gha-read-helm-chart#4]
Would it be possible to expose a charts values (as in `values.yaml`) in some way? I'd like to be able to query a chart for a specific value, for example:

```yaml
steps:
- uses: actions/checkout@master
- name: Read Helm Chart
  id: chart
  uses: jacobtomlinson/gha-read-helm-chart@master
  with:
    path: dask
- name: Print outputs
    run: |
    echo "Tag Version - ${{ steps.chart.outputs.values.worker.image.tag }}"
```
